sudo: required 
dist: trusty 
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - UPSTREAM_WORKSPACE=file
    - ROS_PARALLEL_JOBS=-j4
  matrix:
    - ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="jade" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
matrix:
  allow_failures:
    - env: ROS_DISTRO="jade" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - env: ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - travis_wait 60 .ci_config/travis.sh
#  - ./travis.sh  # Enable this when you have a package-local script 
