joint_names: ["servo_pan","servo_tilt"]

# single positions
home: [[0,0]]
left: [[-1.57,0]]
leftdown: [[-1.57,-0.8]]
leftuphalf: [[-1.57,0.4]]
right: [[1.57,0]]
rightdown: [[1.57,-0.8]]
rightuphalf: [[1.57,0.4]]
down: [[0,-0.8]]
downhalf: [[0,-0.4]]
up: [[0,0.8]]
uphalf: [[0,0.4]]
rightdownhalf: [[1.57,-0.4]]
leftdownhalf: [[-1.57,-0.4]]

# trajectories
mapfull: [up, rightuphalf, uphalf, leftuphalf, left, home, right, rightdownhalf, downhalf, leftdownhalf, leftdown, down, rightdown, home]
scan: [one_rot,home]